# Generated by Django 4.2.5 on 2023-10-05 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='user',
        ),
        migrations.AddField(
            model_name='logger',
            name='level',
            field=models.CharField(default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='logger',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='logger',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
