version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    
  django_app:
    image: my_app:latest  
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - D:\meduzzen_back\medzzen_back:/app 
    ports:
      - "8000:8000"  
    depends_on:
      - db  # Depends on the PostgreSQL service
      - redis  # Depends on the Redis service

volumes:
  postgres_data: