version: '3'

networks:
  regular_network:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - regular_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
      - regular_network
    ports:
      - "6379:6379"
    
  django_app:
    image: my_app:latest  
    command: python manage.py runserver 0.0.0.0:8000  
    networks:
      - regular_network
    volumes:
      - .:/app 
    ports:
      - "8000:8000"  
    depends_on:
      - db  # Depends on the PostgreSQL service
      - redis  # Depends on the Redis service

volumes:
  postgres_data: