# Generated by Django 4.2.5 on 2023-10-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='companies',
        ),
    ]
