# Generated by Django 4.2.5 on 2023-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_members_delete_companymembership'),
        ('accounts', '0003_remove_customuser_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(related_name='companies_member', related_query_name='company_member', to='companies.company'),
        ),
    ]
