# Generated by Django 4.2.5 on 2023-10-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_company_members'),
        ('accounts', '0004_customuser_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='companies_member', related_query_name='company_member', to='companies.company'),
        ),
    ]
