# Generated by Django 4.2.5 on 2023-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
