# Generated by Django 4.2.5 on 2023-10-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_administrators'),
        ('accounts', '0007_customuser_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='administered_companies',
            field=models.ManyToManyField(blank=True, related_name='company_administrators', related_query_name='company_administrator', to='companies.company'),
        ),
    ]
