# Generated by Django 4.2.5 on 2023-10-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
