# Generated by Django 4.2.5 on 2023-10-22 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_company_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='member_companies', related_query_name='member_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
