# Generated by Django 4.2.5 on 2023-10-22 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0008_remove_company_members_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='members_company', related_query_name='member_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompanyMembership',
        ),
    ]
