# Generated by Django 4.2.5 on 2023-10-22 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0009_company_members_delete_companymembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members_company', related_query_name='member_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
