# Generated by Django 4.2.5 on 2023-10-27 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0011_company_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='administrator_companies', related_query_name='administrator_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
