# Generated by Django 4.2.5 on 2023-10-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_company_administrators'),
        ('quizzes', '0002_answer_created_at_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
