# Generated by Django 4.2.5 on 2023-11-09 21:37

from django.db import migrations, models
import django.db.models.deletion

def repopulate_quiz_results(apps, schema_editor):
    QuizResult = apps.get_model('quizzes', 'QuizResult')
    QuizAttempt = apps.get_model('quizzes', 'QuizAttempt')

    quiz_attempts = QuizAttempt.objects.prefetch_related(
        'quiz',
        'user',
        ).all()

    for quiz_attempt in quiz_attempts:
        QuizResult.objects.filter(quiz=quiz_attempt.quiz, user=quiz_attempt.user).update(quiz_attempt_id=quiz_attempt.id)

class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20231107_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='quiz_attempt',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, 
                to='quizzes.quizattempt',
                null=True),
        ),
        migrations.RunPython(repopulate_quiz_results, migrations.RunPython.noop),

    ]
