# Generated by Django 4.2.5 on 2023-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0004_alter_companyinvitation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='status',
            field=models.CharField(choices=[('invited', 'INVITED'), ('requested', 'REQUESTED'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED'), ('canceled', 'CANCELED')]),
        ),
    ]
