name: Django Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up ruff
        run: pip install ruff

      - name: Linting
        run: ruff check ./ --fix

      - name: Set up environment
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Docker image
        run: docker build -t my_app .

      - name: Build and run Docker containers
        run: docker-compose up --build -d

      - name: Run tests
        run: docker-compose exec django_app python manage.py test

      - name: Stop and remove Docker containers
        run: docker-compose down
  
